module.exports = [
    {
        title: "The Rustling of the Sea",
        paragraphs: [`"I thought I told you about playing in the sand." Her grandfather's voice, while stern, wasn't unkind. "Some people are so careless with glass." He sighed. Wrappers, bottles, in time all found their way to his little island, to his lighthouse. "Get ready, this will sting." He held her hand over a small sink on the outside of his house and poured cold soapy water over the gash in her left palm. "I'm afraid this will slow down your playing, dear, at least for a few days."`,
            "",
            `It was winter, the sky was dark grey and the sea breeze blew cold with a bitter bite that made her tan skin feel taut and uncomfortable. Her eyes were wide and the tears she fought to keep there made them look glassy and brittle. She was a strong girl, seven years old, five teeth already taken by the faeries, and as far as she was concerned girls her age didn't cry. That's why it bothered her so that her lower lip was shaking without her permission. "I'm fine," she wanted to say, but if her grandfather understood the half-mumble, half-squeal that came out of her mouth through her grey scarf, she'd have been surprised. She pulled the scarf down and tried again. "I'm fine." It wasn't much better, there was something stuck in her throat that made her words feel sticky, made them hard to decipher.`,
            "",
            `"It was a clean cut, you'll be okay; a bit deeper though and you would have needed stitches. You're a lucky girl, you know that?" He ruffled her hair. "You will need to wear this bandage though, for a while. Think you can handle that?"`,
            "",
            `She nodded. "Yes, Dado." `,
            "",
            `He smiled and the wrinkles in his face deepened. "That's what I like to hear!"—He extended the bandage to her— "Smell this, Bronagh. Good, isn't it?"`,
            "",
            `She nodded again. The bandage was covered in a moisty snot-coloured substance that somehow managed to smell minty and almost sweet. It loosened the words in her throat, helped fight her tears. "What is it, Dado?"`,
            "",
            `"A secret the forest gave me," he said smirking as he tended to her hand.`,
            "",
            `Her eyes grew even wider. Her grandfather had promised they'd visit the forest that grew near the shore on the mainland, she'd always wanted to go. They'd take her grandfather's boat and dare the sea, waves like rollercoasters in the park her parents had taken her to in the summer—only bluer and scarier. An adventure, she thought.  They'd tie the boat to the squeaky dock and hike a mile up the blackened cliffs and walk through the tall trees. An adventure of our own. "Will you tell it to me? The secret, Dado?"`,
            "",
            `"I'm afraid not Bronagh," he said oddly serious. "You see, we can only share our own secrets; and the only secrets we know are the ones shared with us. And, well, our own of course." He gave her a gentle smile.`,
            "",
            `She answered with a scowl. "Dado that's not fair! It's your secret! Tell me so I can have a secret too!"`,
            "",
            `"Oh, but it's not my secret, is it dear? It's the forest's." A glint flitted in his green eyes and Bronagh's heart beat a little faster, she wanted to find out what he meant.`,
            "",
            `"But then I have no secrets, Dado," she said in a small voice.`,
            "",
            `"You'll have your own in time, don't worry. Maybe one day the forest will tell you a secret too. Maybe it'll be the stars. Maybe you'll hear it from the charms. Or maybe," —he gestured beyond the lighthouse— "you'll hear it from the sea. But you must pay attention and make sure your ears are open, Bronagh, for secrets are whispered."`,
            "",
            `Her hand all but forgotten, she looked at him, eyes full of wonder. She could hear the ocean all around her. Waves receding, dragging across the sand, their sound much like a whisper. She smiled a quiet smile, distinctly hers.`,
            "",
            `"In fact, you know what? There's lasagne in the oven, it should be almost done. We'll have dinner and get warm; and we'll listen for a secret. How does that sound?"`,
            "",
            `Bronagh pursed her lips. "Do you think I'll get a secret Dado?"`,
            "",
            `"Something's always whispering dear, we'll just have to see if we're good enough listeners."`,
            "",
            `"I'm a good listener."`,
            "",
            `Her grandfather smiled resting his hand on her head. "Yes, I think so."`,
            "",
            `Bronagh returned his smile. "What will it be Dado, the secret?"`,
            "",
            `"Dinner first, dear. Dinner first." She nodded and pulled her scarf back up to her mouth, he had always told her she should watch for the cold, it sneaks in through half-open mouths and makes people's throats coarse and painful. Her grandfather smiled at her and offered her his hand. "Let's go."`,
            "",
            `They walked into the house together. It wasn't a big place, two bedrooms, a bathroom, a kitchen and a living room. The far wall was concrete as it was built against the back of the lighthouse, but the others were old wood, at places chipped enough the wind blew through, whistling like a boiling teapot. A gentle electric buzz from the heater at the corner of the room filled the air. She took off her jacket and her boots and lowered the scarf but kept it on, she didn't quite trust the air just yet, not until it was toasty, and she could feel her toes again.`,
            "",
            `Not long after, Bronagh sat at the kitchen counter, her plastic fork cutting through the four-layered lasagne with ease. The smell of rosemary, garlic and pepper rising in vapour, melting together with mozzarella cheese and béchamel, and homemade Bolognese sauce. In her left hand, toasted bread lightly coated with olive oil, fine herbs, and parmesan. Her grandfather drank red wine; she, sparkling cranberry juice. Her grandfather's lasagne had always been her favourite. Grown-up food, she thought. It made her feel older and proper. He'd make it every winter she came visit to his house and dinner was a quiet time as she busied herself eating. But tonight, she was restless. Fork held like a club, manners mostly forgotten, legs repeatedly bouncing against the kitchen counter.`,
            "",
            `"It's great Dado. But—"`,
            "",
            `"But can I tell you a secret now?" He smiled. He knew what she wanted.`,
            "",
            `Bronagh smiled back, a cranberry juice moustache crowning her upper lip.`,
            "",
            `"All right, wait here. I won't be long." He left the room, his feet made no sound. `,
            "",
            `Bronagh tilted her head slightly, like a confused puppy. There were times she thought her grandfather was odd. He was very fun to be around but sometimes he would whisper things she didn't quite catch, and if she caught them she wasn't sure she understood them, at times it didn't even sound like English. Last night she told him she'd heard something outside her window, he knelt beside her bed and pulled a dull silver coin from behind her ear. There was a funny letter on one side and a tree on the other, it was thicker and heavier than the coins in her piggy bank back home, less round too. It would bring her luck, protect her, keep the wisps and hags away, he told her. She had half a mind he was a wizard. `,
            "",
            `A minute or two later he came back with a black velvet pouch and set it down at the table. It rattled a little, reminding her of rain.`,
            "",
            `"What is that Dado?"`,
            "",
            `"They're everything dear. They're small pieces of everything. Come on. Finish your food and I'll show you before you go to bed."`,
            "",
            `Bronagh hurried to eat the last of her lasagne and set the plate in the sink. "Okay, I'm ready."`,
            "",
            `Her grandfather pulled the pouch open. Inside Bronagh saw something she could only describe as pebbles; but these pebbles were glossy black, almost polished, speckled with milky white dots that looked like stars, and carved with letters she didn't recognize. They were all different in size and they made her feel like something walked in the small of her back, all the hairs in her arms standing as if pulled by static. "These are runes Bronagh." Her grandfather whispered. "They tell stories of the universe and the universe tells stories of them."`,
            "",
            `"They're beautiful, can I hold one?" she said, her eyes lost in them.`,
            "",
            `He smiled. "Not yet dear, let me show you something first."`,
            "",
            `"Aren't these the secret?"`,
            "",
            `"Not quite. It's what they can tell us that's the secret."`,
            "",
            `"What do you mean Dado?"`,
            "",
            `Her grandfather smiled again. "These runes are like the forest, Bronagh, deep-rooted and old; endless, too, like the sea. There's a lot to learn if you know where to look." He plunged his hand into the pouch and threw the runes into the air in a practiced motion. They flew high and seemed to hang in the air for an odd amount of time as the yellow light of the kitchen's bulb sparkled off their polished surface like fireworks. They hit the table on the way down and didn't bounce at all.  "Let's see," her grandfather said. `,
            "",
            `Bronagh looked at him and kept quiet, her eyes wide. He studied the runes quietly for a while and his face grew grim, lips tightened and brow furrowed he sighed. "Laguz, Rhaido, Isa, Perthro, Eihwaz. Merkstave."`,
            "",
            `Bronagh's smile was broad. That wasn't English. Not at all. She wondered if it was a spell and tried repeating it, but the words were unclear and, in her mind, sounded much like leaves stirred by wind and she realised she couldn't remember them one bit. She looked at her grandfather again and he looked old. She hadn't noticed before. His hair was dirty grey and his skin loose and carved with worries around his eyes and his mouth. "What is it Dado? Are you okay?"`,
            "",
            `"Oh, nothing dear. Yes, I'm fine" He smiled. `,
            "",
            `"So, what's it saying? What's my secret?"`,
            "",
            `"Your secret." He breathed in and closed his eyes for a second. "All right, so, what did I say about secrets earlier?" He asked cheerful once more.`,
            "",
            `"That you'd tell me one after dinner. I had dinner already."`,
            "",
            `Her grandfather smiled, "not that part. That you ha—"`,
            "",
            `"That I have to listen! Yes. See! I remember!"`,
            "",
            `"That you do Bronagh. All right, come here. Listen closely." He picked her up, sat her on his lap. "Look at this one, this—"`,
            "",
            `"That one's on my coin!" Bronagh said producing the coin her grandfather had given her.`,
            "",
            `Her grandfather laughed a deep laugh that made Bronagh feel warm and safe. She pulled her scarf off and wrapped it around her arms. "Yes, dear. Keep that coin with you, okay?"`,
            "",
            `"I will dado," she said and pocketed the coin.`,
            "",
            `"Good," he said smiling. "Now, I need your help."`,
            "",
            `Bronagh nodded, her lips tight, resolute. "I'm ready Dado. What do I do?"`,
            "",
            `"Cup your hands for me. That's it," he said as he dropped a few runes into her hands. "Now throw them on three, all right? Get ready. One. Two. Three." She threw the runes and as before they landed still in the table, like they were too heavy to bounce. "Well done dear, now let's take a look." Her grandfather studied the runes a second time. "Good, good that's much better." He picked Bronagh up and sat her on the table in front of him. "Now Bronagh listen, it's important. You'll find it where the sea and the forest cleave stone."`,
            "",
            `"Where the sea and the forest cleave stone." She repeated. "What does it mean Dado?"`,
            "",
            `"I'm sure we'll find out soon, but it's time for bed now."`,
            "",
            `"Dado I'm not even sleepy! And I don't understand my secret it's not fair."`,
            "",
            `Her grandfather looked at her curiously. "Don't worry, these things take time. It'll make sense soon. Trust me. It's time for bed now, go get ready I'll go tuck you in."`,
            "",
            `Bronagh sighed, she wasn't tired at all, but she knew her grandfather and if he didn't budge the first time he never would so she jumped down the table and readied for bed. She could hear the opening and closing of cabinets and drawers coming from her grandfather's bedroom as she brushed her teeth. "I'm ready." She called.`,
            "",
            `Her grandfather walked in a minute later, he was carrying an aquamarine knapsack just her size. "I think it'll rain tonight; you know how the lights tend to go out so keep a torch nearby. Here, this is for you," he said handing her the knapsack and resting his hand on her head.`,
            "",
            `"What's in it Dado?" She yawned.`,
            "",
            `"It's for our trip to the forest, I was thinking, if the day allows we could go tomorrow. How does that sound?"`,
            "",
            `"That would be amazing!" She yawned again, his hand felt heavy on her head and she was suddenly very tired. `,
            "",
            `"It will be fun, maybe your secret will make sense there. Don't forget your coin." He pulled her coin out from seemingly nowhere, placing it on her hand. Bronagh smiled and rested her closed hand on her chest and fell asleep.`,
            "",
            `**`,
            "",
            `Lightning ripped the ether and rain fell thick as curtains on Bronagh's grandfather. He was walking around the house screaming indecipherably, waving an old yew cane his wife had given him before she passed. When he walked back inside his beard was plastered against his red face and he was out of breath. Outside it seemed the sky was falling and the sea tried to push it back up. He sniffled. Around him the wooden walls creaked as they shook in the wind. He rested on the cane, its yellowing knotted wood reached from the floor in a vague S shape, the walls will hold, he thought, as they have for many a storm before. He sat on his chair near the heater facing Bronagh's door and rested the cane on his lap. They will hold; and if they don't there's always the lighthouse, he thought. The rain picked up as did the wind but soon it was all background noise and his eyelids were heavy. Very heavy indeed. He too fell asleep.`,
            "",
            `He woke up to the loud crack of wooden planks splintering, pulled from the walls by a sudden gust of wind. "Bronagh!" He ran to her room to find her wide awake fastening her yellow raincoat. "Get your knapsack honey, we're going now." There was another crack and the sound of glass shattering, now he could feel rain wetting his back as he stood under Bronagh's doorframe.`,
            "",
            `"Do you have the coin?"  He asked worriedly.`,
            "",
            `"I do," she said as she pulled her knapsack on. "Where are we going Dado?"`,
            "",
            `"The lighthouse." He grabbed her hand. `,
            "",
            `They ran out of the house and made for the lighthouse's thick steel door. It was a short walk but the wind blew strong and threatened to topple them if they weren't careful. The rain was so cold it felt like needles, it made it hard to breathe.`,
            "",
            `"Dado stop."`,
            "",
            `"What? Tell me inside!"`,
            "",
            `"No! Dado, stop!`,
            "",
            `"What?"`,
            "",
            `"Look." She pointed up.`,
            "",
            `Above, lighting spread through the sky like a wide intricate spider web, thunder grumbled and they felt the wet hairs on their arms rise. Bronagh's grandfather pulled her into his arms falling backwards and for a second it was daybreak as a branchlike lightning bolt blew half the lighthouse apart—a moment later a bang like crashing cars erupted from the ground beneath them. Bronagh stared confused, silent. The house was gone crushed under the lighthouse's rubble, small fires started and were quickly put out by the unrelenting rain.`,
            "",
            `He couldn't move, his knees were stiff and Bronagh was heavy and static. He felt his back heat up as he heaved in air, the warmth spread to his hands and his fingers curled around the yew cane. Already the sky threatened to light up as before and strike down whatever stood there, he had to get Bronagh off the island. He pushed his weight into the cane and stood up, the boat was their way out. He walked and the rain didn't lessen, his clothes weighed a thousand pounds and it felt like time itself was pulling on him every step until he got to the boat. Minutes later they were sailing mainland.`,
            "",
            `It was dark, the ocean swelled illuminated only by lighting and their boat was so small. The shore they sought just three miles away but the waves were tall as redwood, the engine sputtered struggling with more water than it should handle. The sea, the wind and the rain rocked the boat and Bronagh kept silent, not knowing what to do she clung to her grandfather's chest. `,
            "",
            `"It'll be okay, it'll be okay," he said and said and until his throat was coarse and land was no closer. The engine stalled and it didn't turn back on, the current took over.  They slowed down as they got to a wave's crest, then, slowly, the boat's bow tipped down and he held Bronagh, tight, close to his chest. "It will be okay." They didn't stand a chance, the boat plummeted down and hit the trough and it was all darkness.`,
            "",
            `**`,
            "",
            `She woke up so cold she was shivering. There was sand on her hair and blood on her mouth, she'd bitten her lower lip in the fray. Fighting the spinning of her head she slowly sat up. It was near morning, fog spread all around her covering the beach. The rain had finally stopped. Her hand hurt, the bandage was gone and it looked a bloody mess, every beat of her heart making it pulse in a nasty way. She looked away—grains of salt clung to the lashes of her brown eyes. When she stood up her sight blackened, she was dizzy and her stomach nearly betrayed her, but she managed.`,
            "",
            `By some miracle it seemed nothing was broken, just badly bruised. Still in one piece she figured she could walk, so she took a deep breath. It was hard to keep standing, her back felt the pull of her drenched knapsack and it took a while for the world to finally stop spinning under her.  When it did she noticed her grandfather was nowhere to be seen and her heart dropped. "Dado! Dado! Where are you!" But it was just the waves lapping at her legs that came back as an answer.  Her eyes began to water and she let out a small gasp. No, she told herself. I'm a strong girl, and I don't cry.. Her lips tightened because she didn't trust herself, her hands balled up into fists and she begun to look around. `,
            "",
            `The first light cut through the fog delicately, its warmth slowed Bronagh's shivering, and the fog begun to dissipate. Behind her only a vast ocean and to her sides sand as far as the eye could see; but ahead, a climb up black rocks that lead into the forest. The forest. She faced the rocks, it was her only choice, if he wasn't in the beach he must be up the cliff, somewhere in the forest. She nodded. She could make the climb. `,
            "",
            `Morning had come in full by the time Bronagh reached the top of the cliff. Though it had been easier than she had expected, she was still tired and her knees and arms sported new scrapes. The throbbing in her hand synched with a headache slowly growing in the back of her head and she still couldn't see him anywhere. "Dado! Dado!" she called. It was only dead leaves stirred by the wind that answered this time. `,
            "",
            `The trees were sparse near the cliff so standing the edge she could see far. The ocean spread until it met the sky, her grandfather's island was nowhere to be seen, to her left and to her right, only the forest. She'd have to walk in deeper. Her eyes narrowed. She was a strong girl, seven years old, five teeth already taken by the faeries, so she turned from the cliff and went in.`,
            "",
            `Soon the cliff was lost, the forest was dense and the pine needles sharp, they scratched her tan cheeks red. Time spread out like spilled water, as it usually does among tall trees, long days of green light and short shadows muddy even practiced minds. The smell of moss covered even the saltwater breeze and crickets sang somewhere hidden. She walked until her thighs begun to cramp and beg to stop and her shins felt splintered. Every so often she would call for her grandfather but there never was an answer. `,
            "",
            `It was hard to see farther than a couple feet in any direction, the brown-grey trunks formed a tight mesh that made her feel closed in. She had no idea how to go back to where she'd come from so she kept walking further in. Eventually her throat was coarse from yelling so she stopped and walked in silence. Her whole body begged her to rest, it had been who knew how many hours, she just knew she wanted to stop. It's almost bedtime, she thought but couldn't be sure. She would need shelter for the night.`,
            "",
            `It worried her, not having found her grandfather. The thought grew slowly. Like a crack on ice it made her feel unstable and a step away from needle-sharp water. And as she walked she felt the weight of her steps make the ice weaker and weaker until only a frail sheet of clear ice kept her from the dark water. What if he's dead? There was something stuck in her throat again and her eyes began to fill with tears and she couldn't help to be afraid. "Dado. Where are you?" Her voice was just a thin whisper, raw from screaming for him all day. I mustn't cry, she told herself again. With a bite to her lower lip she stuck her hands in her pockets for warmth, it was getting colder.`,
            "",
            `Her fingers closed over a thick and oddly-shaped thing. It felt warm and smooth and it took her only a second to recognise and pull it out. The silver coin her grandfather had given her. She smiled. There it was, the tree and the funny letter he showed her in the runes just the day before. It would keep her safe, he had told her. "Dado please," she whispered. "What do I do?" Suddenly the coin began to heat up and a second later it was too hot to hold, so with a scream she tossed it away.`,
            "",
            `The coin flew through the air to her left, somehow managing to miss all the branches landing nearby but out of sight. Bronagh quickly ran after it, flitting through the trees like a faerie. She could see it a few steps away; it had fallen on a bed of leaves that had been dead for so long they were nearly white. She knelt down to pick it up and noticed how soft the leaves felt. Almost instinctively she sat down. Her back found itself resting against the roots of what looked like a windblown oak tree. Odd, she thought there were only pines in the forest. She let out a sigh, she was tired. Holding the coin in her hand she looked up and noticed how the oak's leaves intertwined with the nearby pine needles forming a sort of canopy that kept most of the wind at bay. I could sleep here, she thought. `,
            "",
            `Her stomach groaned, last she'd eaten was the lasagne and she didn't know how long ago that had been. Thankfully this nook she'd found was dry and as far as dead leaves went it was pretty comfortable, that and now that her knapsack was dry and it was sitting it wasn't as heavy as it was before. The knapsack, her eyes widened. He said it was for the forest, maybe there's something to eat— she took it off and laid it on her lap.`,
            "",
            `Some of what he had packed the water had ruined: A lighter that wouldn't spark, a beige mass of crumpled paper Bronagh guessed had once been a map and a compass that just didn't point north. And some, luckily, survived. Like a bottle of water, she avidly drunk from, and a tin can full of the minty paste her grandfather had used for her wound. She rinsed her hand with a little water and covered the gash with the paste, instantly the pain lessened and she felt better. What made her happiest, though, was the Tupperware-protected, avocado, cheese and tomato sandwiches. Though they were soggy and the tomato was warm and gooey, she had never eaten anything better. It felt like he was here and she was safe. So when the night came and the green light gave way to cool moonlight, and when the shadows grew around her and the winter chill pricked her nose, Bronagh wasn't afraid. Twice, the shelter and the food, her grandfather had saved her in the forest, twice she had known she wasn't alone. She would find him in the morning, she was sure.`,
            "",
            `She woke up strong, her hand wasn't bothering her anymore and yesterday's scratches felt only like paint chipped from a still-strong wall. She had saved a sandwich she had for breakfast. She stood up and tossed her coin, "Where to Dado?" she said as she caught it before it reached the ground. Keep your ears open, Bronagh, for secrets are whispered. Her eyes closed as she took a deep breath, coin held in her fist close to her chest. `,
            "",
            `The sound was distant but familiar. She had heard it every morning since her parents brought her to her grandfather's at the start of the holiday. It came from just outside her room's window. Sometimes it calmed her, lulling her to sleep, others, like a night ago, it frightened her reminding her she was small. It was the rustling of the sea she heard. The crash of waves against rocks somewhere close, in fact if she thought she could taste salt in the air. `,
            "",
            `The forest went for miles in every direction and the ocean seemed nowhere near but the sound didn't lie. It took her a while but eventually she figured that the sound was coming from somewhere behind the tree she'd slept under. A more in-depth look revealed a clearing in the roots of the old oak, a burrow of sorts that smelled like the sea. The coin in her hand feels heavy, like it wants it to climb down and her heart is bursting. He must be down there, she thought. She was sure. He was waiting for her, he was so close and the sea was there too. Where sea cleaves rocks he had said. He was there and she could almost smell his cologne. She had to climb down, she knew it in her heart it was what she must do.`,
            "",
            `It was a long and narrow tunnel, sometimes she even had to tuck in her tummy to fit through, it took her more than an hour but eventually she came out the other side. `,
            "",
            `She stood in wet stone; a grotto carved by years of saltwater, hidden somewhere deep beneath the forest. It's a small place, beautiful in the way secrets often are, but small and bare, with no nooks to hide in or large rocks to crouch behind. He wasn't there.`,
            "",
            `The cave's mouth opened to a gentle sea, it was the first good look at the sky she had had since she stood at the edge cliff a day ago. In the distance she could see her grandfather's island, half the lighthouse still stood, proudly so, even. `,
            "",
            `She found a place to sit at the edge of the rock, the waves soon wetted her dangling legs, the water is warm and the sky seems to have forgotten the storm entirely. Not a cloud to see. `,
            "",
            `"Dado," she said, not a scream, a muttering for her only. "I thought you'd be here." Her hand was open and resting on her lap. Behind the dried up paste the cut seemed to have mostly disappeared, it didn't hurt anymore. She placed the silver coin with the funny letter and tree on top of it. "Where are you?" she asked with a small voice again and then she fell silent and just sat there. The waves pulled and pushed like they are wont to, as time passed they crashed louder and louder against the cave. Eventually it was loud enough, she decided, she had been a strong girl already, it was okay now, in that place no one would hear, no one would know, it would be her secret. `,
            "",
            `She was woken up by bright searchlights from a coastguard boat. It was a clear night and soon there was people in her cave with white clinical torchlights devoid of warmth. The seamen didn't ask many questions, that was fine with her, she didn't want to talk. A man in a blue uniform picked her up and carried her aboard.`,
            "",
            `**`,
            "",
            `14 years have passed since the storm, since her stroll in the forest and her nap in the cave. `,
            "",
            `They found her grandfather's body a week later. It showed up one afternoon at a nearby beach, spooking some tourists. They made the right calls and soon the body was carried away to a metal table in the city. His skin had bloated, it was grey and very fish-like, nibbled by opportunistic sea critters who had a penchant for easy meals. It was a closed casket funeral. That was the first time she saw her father cry, her mum stood stoic, holding his hand. `,
            "",
            `Her parents had gone looking for her as soon as the storm started, they lived in the city and it took them almost two hours to get to the beach. They saw the lightning strike the lighthouse in the distance. The coastguard refused to start the search until the storm subsided. By then it was, of course, too late. They worried more than they ever had for two days and then they found her. Her eyes were puffy and red when the coastguard brought her to them. They didn't mention it.`,
            "",
            `It's mid-December. She's on winter break. It is a different knapsack now but it's the same aquamarine that one had been. This time it's dry and filled with enough food and water for two days. She's wearing a waterproof jacket, a warm sweater and comfortable shoes. She doesn't have a compass but she doesn't need it, her phone has a full charge and she's brought four extra batteries. Earlier that morning she called her dad as he wanted and assured him she'd be all right and no, thank you really, but he doesn't need to come down with her, and yes she brought water and a torch and everything else he wonders.`,
            "",
            `The trees seem shorter and when she looks up she can see the sky. With help from a map she pulled up in her phone the forest is no longer maze-like. A proper middle age woman chimes on every so often letting her know how far she's from where she's going. She walks through the tall trees, it rained recently and her nose is full of the smell of wet dirt. After a while a gentle chirp from her phone let's her know she's arrived.`,
            "",
            `Its roots have grown longer and thicker, but it's still the oak she remembers. With time, and a pocket knife, she's soon cut away enough of the roots to fit through the opening to the tunnel she climbed all those years ago. It seems the years have worn in it wider and she's thankful. `,
            "",
            `The cave seems smaller than she remembers, it takes her less than ten steps to reach the edge between the rocks and the sea where she sits down. She puts her phone away and closes her eyes to listen. When she gets hungry she nibbles on a tuna sandwich she made the day before, she's not a good cook. `,
            "",
            `Soon the sun is setting, coming down in peach and red light that glints on the water's surface. Her hand reaches into the inside pocket of her jacket and she produces her coin. The funny letter, she learned from the internet, comes from Elder Futhark and the tree is Yggdrasil. They have faded a little with time but they're still there. She takes a deep breath. "Dado," she says.`,
            "",
            `It's hard not to feel disappointed. He had been a hero. He had been more than that. He had been otherworldly. Her bridge to the faeries and incantations she so wished were real. When she was younger she was sure he, like her, would live forever. But he died. And now her parents are getting older and there is grey in their hairs. And now she herself is older and no longer feels enduring. She thinks she should know what to do but she has no clue where to go, what to do. Her university is nearly done, after that she doesn't really know what follows. `,
            "",
            `She heard him the night of the storm, outside her window, screaming nonsense to the winds. He knew it was going to rain. They had heard the weather report on the radio earlier that morning, seen the black clouds forming all day long. He knew and decided to stay. And when the storm got scary he went outside and shouted for a while and then promptly fell asleep on his chair.`,
            "",
            `"Dado," she says and her fist tightens around the coin like it has many times across her life when she just doesn't know.`,
            "",
            `It's her fourth time in the cave. Once when she was 14 and she caught her mum cheating on her father with a friend from work, and she didn't know if she should tell her dad—the divorce was messy but it was fine now. Then at 16 when her best friend Jenna told her that she was in love with her and could she please be her girlfriend, and she didn't know how to answer—she and Jenna no longer talk. At 18 she came when her mother fell ill and her new husband's family didn't give her much time with her at the hospital, she didn't know how to feel— it was breast cancer and three years later her mom still fought. `,
            "",
            `Today she's 21 and this time she's doesn't quite know why she"s come.`,
            "",
            `"Dado," she says. "I think I just miss you." She goes quiet for a while. "You were stubborn, weren't you? Dad says I got that from you. Says you were so sure that house could take on any storm. Says you miscalculated. Why didn't you leave before it rained? It's been so long. `,
            "",
            `"Lately I forget what you looked like, my dad sent a picture to help me remember…I wonder what you'd think of dad, he's got your nose. Last year he grew a beard. I wasn't convinced at first, if you must know, but its grown on me. I wonder what you'd think of me. Dad says you scolded him for being 'so scientific, so boring and square' when he went into medicine school. I'm studying chemistry now Dado, I wonder what you'd say about that."`,
            "",
            `The moon has come out to a clear, many-starred winter sky. The ocean looks dark and sluggish, like it's carrying things it can't let go of. It crashes against the rocks of her cave and then pulls back tiredly.`,
            "",
            `"Dado," she says.`]
    }
]